### ISSUE TITLE
运行时出现错误

### ISSUE THREAD

**Issue by recall704** [lbp0200/PRCDNS#2]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/site-packages/PRCDNS/server.py", line 64, in send_resp
    google_dns_resp = fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.5/site-packages/PRCDNS/proxy_client.py", line 22, in query_domain
    return await ProxyClient.fetch(session, url, proxy)
  File "/usr/lib/python3.5/site-packages/PRCDNS/proxy_client.py", line 16, in fetch
    async with session.get(url, proxy=proxy) as response:
  File "/usr/lib/python3.5/site-packages/aiohttp/client.py", line 587, in __aenter__
    self._resp = yield from self._coro
  File "/usr/lib/python3.5/site-packages/aiohttp/client.py", line 215, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/lib/python3.5/site-packages/aiohttp/connector.py", line 360, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 101] Cannot connect to host dns.google.com:443 ssl:True [Can not connect to dns.google.com:443 [Network unreachable]]
```

然而：

```
/ # ping dns.google.com
PING dns.google.com (172.217.4.174): 56 data bytes
64 bytes from 172.217.4.174: seq=0 ttl=56 time=0.826 ms
64 bytes from 172.217.4.174: seq=1 ttl=56 time=0.687 ms
64 bytes from 172.217.4.174: seq=2 ttl=56 time=0.771 ms
```

**Comment by lbp0200** [comment]
```bash
curl https://dns.google.com/resolve?name=img.alicdn.com
```
有返回吗？

**Comment by lbp0200** [comment]
是不是加了代理？放在VPS上，不用加代理的

**Comment by recall704** [comment]
可以了，系统没有自带 curl
